name: Checkmarx AST Scan
on: [workflow_dispatch]



jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Checkmarx AST CLI Action
       uses: Checkmarx/ast-github-action@2.0.2
       with:
            project_name: small-project
            base_uri: https://eu.ast.checkmarx.net/
            cx_tenant: cx_ast_pm_yoav_ast
            cx_client_id: ${{ secrets.CLIENT_ID }}
            cx_client_secret: ${{ secrets.CLIENT_SECRET }}
            additional_params: --debug  --sast-preset-name "failed preset"




        
    
